version: '3.0'

services:

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
  
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  localstack:
    container_name: localstack_main
    image: localstack/localstack:0.12.17
    ports:
      - 4566:4566
      - 4565:4565
      - 4571:4571
      - 4576:4576
      - 4575:4575
    environment:
      - SERVICES=sns,sqs,s3
    volumes:
      - "./localstack.sh:/docker-entrypoint-initaws.d/ses.sh"

  prometheus:
    image: prom/prometheus:v2.15.2
    container_name: prometheus
    volumes: 
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    network_mode: 'host'

  grafana_8:
    image: grafana/grafana
    container_name: grafana_8
    depends_on:
      - prometheus
    environment:
      GF_SERVER_HTTP_PORT: '3002'
    volumes:
      - ./provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./config.monitoring

    network_mode: 'host' 

networks:
  monitoring:
    driver: bridge
